using System;
using System.Collections.Generic;
using System.Text;
using System.Net.Http;
using System.Net.Http.Headers;
using Newtonsoft.Json;
using Xamarin.Forms;
using System.Threading.Tasks;

namespace FitnessApp.Portable
{
    public class WSConsumer
    {
        private static HttpClient restClient;

        public async static Task<List<Unit>> GetUnits()
        {
            List<Unit> units = new List<Unit>();
            // connection to the web service
            string request = "";
            restClient = new HttpClient();
            string value;
            try
            {
                restClient.BaseAddress = new Uri("http://psotty.pythonanywhere.com/units");
                restClient.DefaultRequestHeaders.Clear();
                restClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("text/json"));
                value = await restClient.GetStringAsync(request);
                // TO DO:
                // Get the json data from the web service
                // deserialize the data into units
                units = JsonConvert.DeserializeObject<List<Unit>>(value);
                DependencyService.Get<IMessage>().longtime("Load from Web Service");
            }
            catch(Exception e)
            {
                DependencyService.Get<IMessage>().longtime("ERR: "+e.Message);
                throw e;
            }
            return units;
        }

        public void AddUnit(Unit unit)
        {
            // TO DO:
            // serialize unit in json format
            // send the serialized unit to the web service
            // get the new list
        }

        public List<SportType> GetSports()
        {
            List<SportType> sports = new List<SportType>();
            // TO DO:
            // Get the json data from the web service
            // deserialize the data into sports
            return sports;
        }

        public void addSport(SportType sport)
        {
            // TO DO:
            // serialize sport in json format
            // send the serialized sport to the web service
            // get the new list
        }

        public List<Session> GetSessions()
        {
            List<Session> sessions = new List<Session>();
            // TO DO:
            // Get the json data from the web service
            // deserialize the data into sessions
            return sessions;
        }

        public void AddSession(Session session)
        {
            // TO DO:
            // serialize session in json format
            // send the serialized session to the web service
            // get the new list
        }

        public void SaveUser(User user)
        {
            // TO DO:
            // serialize user in json format
            // send the serialized user to the web service
            // get the id generated by the WS
        }
    }
}
