using System;
using System.Collections.Generic;
using System.Text;
using System.Net.Http;
using System.Net.Http.Headers;
using Newtonsoft.Json;
using Xamarin.Forms;
using System.Threading.Tasks;

namespace FitnessApp.Portable
{
    public class WSConsumer
    {
        private static HttpClient restClient;

        public async static Task<List<Unit>> GetUnits()
        {
            List<Unit> units = new List<Unit>();
            string value;
            try
            {
                // Get the json data from the web service
                // deserialize the data into units
                value = await Connect("http://psotty.pythonanywhere.com/units");
                units = JsonConvert.DeserializeObject<List<Unit>>(value);
                DependencyService.Get<IMessage>().longtime("Load units from Web Service");
            }
            catch(Exception e)
            {
                DependencyService.Get<IMessage>().longtime("ERR: "+e.Message);
                throw e;
            }
            return units;
        }

        public void AddUnit(Unit unit)
        {
            // TO DO:
            // serialize unit in json format
            // send the serialized unit to the web service
            // get the new list
        }

        public async static Task<List<SportType>> GetSports()
        {
            List<SportType> sports = new List<SportType>();
            string value;
            try
            {
                // Get the json data from the web service
                // deserialize the data into sports
                value = await Connect("http://psotty.pythonanywhere.com/sports");
                sports = JsonConvert.DeserializeObject<List<SportType>>(value);
                DependencyService.Get<IMessage>().longtime("Load from Web Service");
            }
            catch (Exception e)
            {
                DependencyService.Get<IMessage>().longtime("ERR: " + e.Message);
                throw e;
            }
            return sports;
        }

        public void addSport(SportType sport)
        {
            // TO DO:
            // serialize sport in json format
            // send the serialized sport to the web service
            // get the new list
        }

        public List<Session> GetSessions()
        {
            List<Session> sessions = new List<Session>();
            // TO DO:
            // Get the json data from the web service
            // deserialize the data into sessions
            return sessions;
        }

        public void AddSession(Session session)
        {
            // TO DO:
            // serialize session in json format
            // send the serialized session to the web service
            // get the new list
        }

        public void SaveUser(User user)
        {
            // TO DO:
            // serialize user in json format
            // send the serialized user to the web service
            // get the id generated by the WS
        }

        public static async Task<string> Connect(string url)
        {
            string value = "";
            // connection to the web service
            string request = "";
            restClient = new HttpClient();
            try
            {
                restClient.BaseAddress = new Uri(url);
                restClient.DefaultRequestHeaders.Clear();
                restClient.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("text/json"));
                value = await restClient.GetStringAsync(request);
                // clean the string to just have the array
                value = value.Remove(0, value.IndexOf("[") - 1);
                value = value.Remove(value.LastIndexOf("]") + 1);
            }
            catch (Exception e)
            {
                throw e;
            }
            return value;
        }
    }
}
